version: 2
updates:
  # - package-ecosystem: "swift"
  #   directory: "/PagerCall.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/"
  #   schedule:
  #     interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
